# -*- coding: utf-8 -*-
"""chat_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Y3DUh_Srfta4swXscsfJO4nvm6RxcuV
"""

!pip install -q gradio sentence-transformers faiss-cpu \
    transformers peft torch PyMuPDF

import os, json, re
import numpy as np
import torch
import faiss
from pathlib import Path
from sentence_transformers import SentenceTransformer, CrossEncoder
from transformers import AutoTokenizer, AutoModelForCausalLM
from peft import PeftModel
import gradio as gr

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

"""Load index and chunks"""

from google.colab import drive
drive.mount('/content/drive', force_remount=False)

DRIVE_BASE = "/content/drive/MyDrive/372-Project"
LORA_PATH  = f"{DRIVE_BASE}/models/lora-coach"

# Load FAISS index and chunks saved from rag_pipeline.ipynb
index  = faiss.read_index(f"{DRIVE_BASE}/models/notes.faiss")
with open(f"{DRIVE_BASE}/models/chunks.json") as f:
    chunks = json.load(f)

print(f"Loaded FAISS index: {index.ntotal} vectors")
print(f"Loaded {len(chunks)} chunks")

"""Load embedder and reranker"""

embedder = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2", device=device
)
reranker = CrossEncoder(
    "cross-encoder/ms-marco-MiniLM-L-6-v2", device=device
)
print("Embedder and reranker loaded.")

"""Load model"""

!pip install --upgrade torchao peft accelerate
BASE_MODEL = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL)
tokenizer.pad_token = tokenizer.eos_token

base  = AutoModelForCausalLM.from_pretrained(
    BASE_MODEL, torch_dtype=torch.float16, device_map="auto"
)
model = PeftModel.from_pretrained(base, LORA_PATH)
model.eval()
print("Fine-tuned model loaded.")

"""Retrieval pipeline"""

def retrieve_dense(query, k=10):
    q_emb = embedder.encode(
        [query], normalize_embeddings=True
    ).astype("float32")
    scores, indices = index.search(q_emb, k)
    return [(int(i), float(s)) for i, s in zip(indices[0], scores[0]) if i >= 0]

def retrieve_and_rerank(query, retrieve_k=10, final_k=3):
    candidates  = retrieve_dense(query, k=retrieve_k)
    cand_chunks = [chunks[i] for i, _ in candidates]
    pairs       = [(query, c) for c in cand_chunks]
    scores      = reranker.predict(pairs)
    ranked      = sorted(zip(cand_chunks, scores), key=lambda x: x[1], reverse=True)
    return [(c, float(s)) for c, s in ranked[:final_k]]

"""Context window manager"""

MAX_HISTORY_TOKENS = 800   # how much history to keep in prompt
MAX_CONTEXT_TOKENS = 1024  # total prompt budget

class ConversationManager:
    """
    Manages multi-turn conversation history with token-aware truncation.

    Tracks:
      - Full message history (never discarded — used for display)
      - Truncated history window (fitted to token budget for each prompt)
      - Retrieved sources per turn (for transparency)
    """

    def __init__(self):
        self.history = []        # list of {"role": "user"|"assistant", "content": str}
        self.sources = []        # retrieved chunks per turn

    def add_turn(self, user_msg, assistant_msg, sources):
        self.history.append({"role": "user",      "content": user_msg})
        self.history.append({"role": "assistant", "content": assistant_msg})
        self.sources.append(sources)

    def get_history_block(self):
        """Return recent history fitted to MAX_HISTORY_TOKENS budget.
        Drops oldest turns first when over budget.
        """
        lines = []
        for turn in self.history:
            role = "Student" if turn["role"] == "user" else "Coach"
            lines.append(f"{role}: {turn['content']}")

        # Trim from oldest if over token budget
        while lines:
            joined = "\n".join(lines)
            tokens = len(tokenizer.encode(joined))
            if tokens <= MAX_HISTORY_TOKENS:
                break
            lines = lines[2:]   # drop oldest user+assistant pair

        return "\n".join(lines)

    def clear(self):
        self.history = []
        self.sources = []

    def turn_count(self):
        return len(self.history) // 2

conversation = ConversationManager()
print("ConversationManager ready.")

"""Prompt builder with history"""

FEW_SHOT_EXAMPLES = [
    {
        "question": "What is the ship of Theseus?",
        "answer": "The Ship of Theseus is a philosophical thought experiment that asks"
                  "whether an object remains the same if all of its original parts are"
                  "gradually replaced. It questions the nature of identity and whether"
                  "continuity comes from physical components or from history and perception."
    },
    {
        "question": "What is existentialism?",
        "answer": "Existentialism is a philosophical movement that focuses on individual"
                  "freedom, choice, and responsibility, arguing that people create meaning"
                  "through their actions rather than discovering a pre-given purpose."
    }
]

def build_prompt(query, retrieved_chunks, history_block=""):
    """Chain-of-thought prompt with conversation history injected.
    History block is empty on the first turn.
    """
    context = "\n\n".join(
        f"[Source {i+1}]\n{c}" for i, (c, _) in enumerate(retrieved_chunks)
    )

    examples = "\n\n".join(
        f"Q: {ex['question']}\nA: {ex['answer']}"
        for ex in FEW_SHOT_EXAMPLES
    )

    history_section = ""
    if history_block:
        history_section = f"""Previous conversation:
{history_block}

"""

    return f"""### Instruction:
You are a helpful AI learning coach. Use the notes below to answer the student's question clearly and accurately.

Examples of good answers:
{examples}
Let's think through this step by step:
1. Identify the key concept in the question.
2. Find the most relevant information in the notes.
3. Explain it clearly for a student learning this for the first time.

### Input:
{context}

{history_section}

{query}
### Response:"""

"""Generation function"""

def generate(prompt, temperature=0.1, max_new_tokens=300):
    inputs = tokenizer(
        prompt,
        return_tensors="pt",
        truncation=True,
        max_length=MAX_CONTEXT_TOKENS
    ).to(device)

    with torch.no_grad():
        out = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=True,
            temperature=temperature,
            top_p=0.9,
            repetition_penalty=1.1,
            pad_token_id=tokenizer.eos_token_id
        )

    decoded = tokenizer.decode(out[0], skip_special_tokens=True)
    if "### Response:" in decoded:
        return decoded.split("### Response:")[-1].strip()
    return decoded

"""chat function"""

def chat(user_message, gradio_history, temperature=0.7):
    """
    Called by Gradio on each user message.

    gradio_history: list of [user_msg, assistant_msg] pairs — Gradio's format
    Returns: updated gradio_history, empty textbox, sources string
    """
    if not user_message.strip():
        return gradio_history, "", "No query entered."

    #Retrieve relevant chunks
    top_chunks = retrieve_and_rerank(user_message)

    #  Build history block from ConversationManager
    history_block = conversation.get_history_block()

    # Build prompt
    prompt = build_prompt(user_message, top_chunks, history_block)

    # Generate answer
    answer = generate(prompt, temperature=temperature)

    #  Save turn to history
    conversation.add_turn(user_message, answer, top_chunks)

    # Update Gradio history (its own format for display)
    gradio_history = gradio_history + [[user_message, answer]]

    #  Format sources for display
    sources_text = f"**Turn {conversation.turn_count()} — Retrieved Sources:**\n\n"
    for i, (chunk, score) in enumerate(top_chunks):
        sources_text += f"**[{i+1}]** score={score:.3f}\n{chunk[:200]}...\n\n"

    return gradio_history, "", sources_text


def reset_conversation():
    """Clear history for a fresh session."""
    conversation.clear()
    return [], "", "Conversation cleared."

"""gradio UI"""

with gr.Blocks(title="AI Learning Coach", theme=gr.themes.Soft()) as demo:

    gr.Markdown("""
    # AI Learning Coach
    Ask questions about your course notes. The coach remembers your conversation.
    """)

    with gr.Row():

        with gr.Column(scale=2):
            chatbot = gr.Chatbot(
                label="Conversation",
                height=500,
                show_label=True
            )
            with gr.Row():
                msg_box = gr.Textbox(
                    placeholder="Ask a question about your notes...",
                    label="Your question",
                    scale=4,
                    lines=2
                )
                send_btn = gr.Button("Send", variant="primary", scale=1)

            with gr.Row():
                clear_btn = gr.Button("🗑 Clear Conversation", variant="secondary")

            with gr.Accordion("Generation Settings", open=False):
                temperature_slider = gr.Slider(
                    minimum=0.1, maximum=1.5, value=0.7, step=0.05,
                    label="Temperature (higher = more creative, lower = more focused)"
                )

        with gr.Column(scale=1):
            gr.Markdown("### Retrieved Sources")
            gr.Markdown("Chunks retrieved from your notes that informed the answer.")
            sources_box = gr.Markdown("Sources will appear here after your first question.")

    with gr.Accordion("Raw Conversation History", open=False):
        history_display = gr.JSON(label="Full history log")
        refresh_btn = gr.Button("Refresh History")

        def refresh_history():
            return conversation.history

        refresh_btn.click(refresh_history, outputs=history_display)

    send_btn.click(
        fn=chat,
        inputs=[msg_box, chatbot, temperature_slider],
        outputs=[chatbot, msg_box, sources_box]
    )
    msg_box.submit(        # also send on Enter key
        fn=chat,
        inputs=[msg_box, chatbot, temperature_slider],
        outputs=[chatbot, msg_box, sources_box]
    )
    clear_btn.click(
        fn=reset_conversation,
        outputs=[chatbot, msg_box, sources_box]
    )

demo.launch(share=True, debug=False)  # share=True gives a public Colab URL