# -*- coding: utf-8 -*-
"""finetune_lora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1498MMy50TaFfZrEOeSdmsGjgRINxslPF
"""

!pip install transformers peft datasets accelerate bitsandbytes faiss-cpu sentence-transformers

"""GPU check"""

import torch
import matplotlib.pyplot as plt
from transformers import (
    AutoTokenizer, AutoModelForCausalLM,
    TrainingArguments, Trainer, TrainerCallback,
    DataCollatorForLanguageModeling, EarlyStoppingCallback
)
from peft import LoraConfig, get_peft_model, TaskType
from datasets import load_dataset

# Confirm GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")
print(f"GPU: {torch.cuda.get_device_name(0) if device == 'cuda' else 'None'}")

"""Load model and tokenizer"""

MODEL_NAME = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token  # required for batching

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.float16,  # saves VRAM
    device_map="auto"           # auto-places on GPU
)
print(f"Model loaded. Parameters: {model.num_parameters():,}")

"""Apply LoRA"""

lora_config = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    r=8,                        # rank — keep low for Colab
    lora_alpha=16,              # scaling factor
    lora_dropout=0.1,           # regularization (dropout)
    target_modules=["q_proj", "v_proj"],  # which layers to adapt
    bias="none"
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()
# Expect ~0.1% of params trainable — that's normal and correct

"""Load & Format Dataset (SFT / Instruction Tuning)"""

# Load Alpaca-style instruction dataset
dataset = load_dataset("yahma/alpaca-cleaned", split="train")

# Filter to explanation/teaching examples for relevance
dataset = dataset.filter(lambda x: len(x["output"]) > 100)
dataset = dataset.shuffle(seed=42).select(range(5000))  # subset for speed

PROMPT_TEMPLATE = """### Instruction:
{instruction}

### Input:
{input}

### Response:
{output}"""

def format_example(example):
    text = PROMPT_TEMPLATE.format(
        instruction=example["instruction"],
        input=example.get("input", ""),
        output=example["output"]
    )
    tokenized = tokenizer(
        text,
        truncation=True,
        max_length=512,
        padding="max_length"
    )
    tokenized["labels"] = tokenized["input_ids"].copy()
    return tokenized

tokenized_dataset = dataset.map(format_example, remove_columns=dataset.column_names)
split = tokenized_dataset.train_test_split(test_size=0.1, seed=42)
train_dataset = split["train"]
eval_dataset = split["test"]

print(f"Train: {len(train_dataset)} | Eval: {len(eval_dataset)}")

"""Training curve callback"""

# Custom callback to record loss at each step
class LossTracker(TrainerCallback):
    def __init__(self):
        self.train_losses = []
        self.eval_losses = []
        self.steps = []

    def on_log(self, args, state, control, logs=None, **kwargs):
        if logs:
            if "loss" in logs:
                self.train_losses.append(logs["loss"])
                self.steps.append(state.global_step)
            if "eval_loss" in logs:
                self.eval_losses.append(logs["eval_loss"])

loss_tracker = LossTracker()

"""Training arguments and trainer"""

training_args = TrainingArguments(
    output_dir="./models/lora-coach",
    num_train_epochs=3,
    per_device_train_batch_size=4,
    gradient_accumulation_steps=4,   # effective batch = 16 (stability)
    per_device_eval_batch_size=4,
    warmup_steps=50,
    eval_strategy="steps",
    eval_steps=100,
    save_strategy="steps",
    save_steps=100,
    logging_steps=20,
    learning_rate=2e-4,
    weight_decay=0.01,               # L2 regularization
    fp16=True,
    load_best_model_at_end=True,     # for early stopping
    metric_for_best_model="eval_loss",
    report_to="none"                 # disable wandb
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    data_collator=DataCollatorForLanguageModeling(tokenizer, mlm=False),
    callbacks=[
        loss_tracker,
        EarlyStoppingCallback(early_stopping_patience=3)  # regularization
    ]
)

trainer.train()

"""Plot training curves"""

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

ax1.plot(loss_tracker.steps, loss_tracker.train_losses, color="steelblue", label="Train Loss")
ax1.set_title("Training Loss Over Steps")
ax1.set_xlabel("Step")
ax1.set_ylabel("Loss")
ax1.legend()
ax1.grid(alpha=0.3)

eval_steps_x = [i * 100 for i in range(1, len(loss_tracker.eval_losses) + 1)]
ax2.plot(eval_steps_x, loss_tracker.eval_losses, color="coral", label="Eval Loss")
ax2.set_title("Validation Loss Over Steps")
ax2.set_xlabel("Step")
ax2.set_ylabel("Loss")
ax2.legend()
ax2.grid(alpha=0.3)

plt.suptitle("LoRA Fine-Tuning Curves — AI Learning Coach", fontsize=13)
plt.tight_layout()

plt.show()

"""As we can see, the training loss drastically decreases in the first few training steps 0-200, but from 200-800 steps it fluctuates while still following a general trend of decline in loss. The validation loss, on the other hand, follows a smoother and more consistent decline over steps, showing the improvement of the model and increased accuracy over training.

Save model
"""

from google.colab import drive
import os


drive.mount('/content/drive')


save_path = "/content/drive/MyDrive/372-Project/models/lora-coach"

if not os.path.exists(save_path):
    os.makedirs(save_path)

model.save_pretrained(save_path)
tokenizer.save_pretrained(save_path)

print(f"Model successfully saved to Google Drive at: {save_path}")

"""Custom generation with temperature sampling"""

def generate_response(prompt, temperature=0.7, max_new_tokens=256):
    """Custom generation with temperature sampling."""
    inputs = tokenizer(prompt, return_tensors="pt").to(device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=True,           # enable sampling
            temperature=temperature,  # controls randomness
            top_p=0.9,                # nucleus sampling
            repetition_penalty=1.1,
            pad_token_id=tokenizer.eos_token_id
        )

    decoded = tokenizer.decode(outputs[0], skip_special_tokens=True)
    # Strip the prompt from output
    return decoded[len(tokenizer.decode(inputs["input_ids"][0], skip_special_tokens=True)):]

# Quick test
test_prompt = """### Instruction:
Explain the concept of gradient descent to a student who is learning for the first time.

### Input:

### Response:"""

print(generate_response(test_prompt))

"""The output is on topic and grammatically correct, which is good, with display of temperature sampling. However, it's factually imprecise with some incorrect information, such as saying that gradient descent is the direction of least curvature, which is incorrect. This is probably due to the model hallucinating from limited training.

This is our iteration 1 baseline model, and I will implement RAG in the next notebook to improve factual precision and correctness of the outputs to give students accurate information when using this model and reduce hallucinations.


"""

